### PR TITLE
Resolve #456 change sequenceTerminals to adjoinedSequences in Adjacency

### LINKED ISSUE #456: Rename `sequenceTerminals` to `adjoinedSequences` in the new Adjacency class in 2.0
During the 12/7/23 SV meeting @d-cameron and the group discussed the new `Adjacency` class and mentioned the need to rename the `sequenceTerminals` attribute to provide a clearer term for what was being represented in that attribute. The term `connection` was offered as a better alternative.

### PR DESCRIPTION
**Pull request by larrybabb**
Resolve #456 
@d-cameron and/or @Mrinal-Thomas-Epic could you please review this and let me know if it okay to merge?

### CODE REVIEW

**Comment by ahwagner** [comment]
@larrybabb is the intended target branch here `main`, or `2.0-alpha`?

**Comment by larrybabb** [comment]
> @larrybabb is the intended target branch here `main`, or `2.0-alpha`?

@ahwagner When I created the PR you said to make it `main` but I think it should be `2.0-alpha`.

**Comment by ahwagner** [comment]
Agreed, `2.0-alpha` is the appropriate branch, sorry for any miscommunication. I have updated the target accordingly.

**Review by ahwagner — APPROVED** [review]
This looks great!

**Pull request merged**
