### PR TITLE
Update validation models

### LINKED ISSUE #405: Update models.yaml
The data in `models.yaml` is invalid. 

For example, `AbsoluteCopyNumber.subject` can be a `CURIE`, `ChromosomeLocation`, or `SequenceLocation` but in `models.yaml` `AbsoluteCopyNumber.subject` is a `Gene`. 

```yaml
AbsoluteCopyNumber:
  - name: ">=3 copies APOE"
    in:
      copies:
        comparator: '>='
        type: IndefiniteRange
        value: 3
      subject:
        gene_id: ncbigene:348
        type: Gene
      type: AbsoluteCopyNumber
```

This is causing tests to fail in [this](https://github.com/ga4gh/vrs-python/pull/114) VRS-Python PR.

### PR DESCRIPTION
**Pull request by korikuzma**
Close #405

- Absolute / Relative Copy Number now have a CURIE as the subject
- Add test models for GenotypeMember + Genotype

### CODE REVIEW

**Review by larrybabb — APPROVED** [review]
i left a comment for @ahwagner and I to discuss, but nothing that should hold this up at this point in time.

**Review by ahwagner — CHANGES_REQUESTED** [review]
I think these tests need to be changed to have a `SequenceLocation` subject–not a `Gene`. We had decided that we wanted to keep these `Location` based and not allow polymorphism. The `CURIE` is for the `Location` ID only.

**Comment by larrybabb** [comment]
> I think these tests need to be changed to have a `SequenceLocation` subject–not a `Gene`. We had decided that we wanted to keep these `Location` based and not allow polymorphism. The `CURIE` is for the `Location` ID only.

I agree. I also think we should make the attribute name as precise as possible with the type. So we should seriously consider changing it to `location` instead of subject (i think).

**Comment by korikuzma** [comment]
@larrybabb @ahwagner Changed the `subject` to be a `SequenceLocation` as seen [here](https://github.com/ga4gh/vrs/pull/407/commits/057342f2da8694eb57c3b2f046044c6b88a76fac).

**Review by ahwagner — APPROVED** [review]

**Pull request merged**
