### PR TITLE
Apply VRS 1.3 CNV changes

### LINKED ISSUE #420: Incorporate 1.3 CNV changes in metaschema-update
Needed for @theferrit32 @larrybabb

### PR DESCRIPTION
**Pull request by korikuzma**
Close #420 

Notes:
- I did not update docs. It seems like these have not been updated in a long time, so we can address this in a separate issue
- In 1.3, EFO's are not curies (i.e., EFO_0030071). I thought there was discussion about changing to CURIEs, so I made that change here

### CODE REVIEW

**Comment by korikuzma** [comment]
Forgot to allow Gene to be the subject

**Comment by korikuzma** [comment]
@ahwagner @larrybabb I'm kind of confusing myself. In [vrs-source.yaml](https://github.com/ga4gh/vrs/blob/main/schema/vrs-source.yaml#L234), there is no Gene in the subject for the Copy Number classes. But in [vrs.yaml](https://github.com/ga4gh/vrs/blob/main/schema/vrs.yaml#L200), there is a Gene in the subject.

**Comment by korikuzma** [comment]
@ahwagner @larrybabb Made the final changes. Ready for review!

**Review by larrybabb — APPROVED** [review]
LGTM

**Review by ahwagner — APPROVED** [review]
LGTM.

**Pull request merged**
