### PR TITLE
update models from 2.0-alpha changes

### PR DESCRIPTION
**Pull request by korikuzma**
Main changes:
- `SequenceReference` digest is `referenceSequence.refgetAccession.split("SQ.")[-1]`
- Copy Number `subject` renamed to `location`

Questions:
- I'm not sure about `SequenceReference`. I currently have it so that `ga4gh_identify` and `ga4gh_serialize` return null. It's under the IDENTIFABLE TYPES sections, so it should return a response for `ga4gh_identify`. Would it just be `ga4gh:{refgetAccession}`?

### CODE REVIEW

**Comment by larrybabb** [comment]
@korikuzma i believe the `SequenceReference` should return exactly the same value that `Sequence` would return.

**Comment by korikuzma** [comment]
> @korikuzma i believe the `SequenceReference` should return exactly the same value that `Sequence` would return.
> 
> SequenceReference is a proxy for Sequence.

@larrybabb can you suggest changes in the file?

**Review by ahwagner — APPROVED** [review]

**Comment by ahwagner** [comment]
> Main changes:
> 
> * `SequenceReference` digest is `referenceSequence.refgetAccession.split("SQ.")[-1]`
> * Copy Number `subject` renamed to `location`
> 
> Questions:
> 
> * I'm not sure about `SequenceReference`. I currently have it so that `ga4gh_identify` and `ga4gh_serialize` return null. It's under the IDENTIFABLE TYPES sections, so it should return a response for `ga4gh_identify`. Would it just be `ga4gh:{refgetAccession}`?

You are correct to have those methods return `null`. There is no need to serialize as there is a custom digest method. There is no identifier and it should not be under identifiable types. See the schema [here](https://github.com/ga4gh/vrs/blob/375cb515876779936c302266de9a60b4b907c8d3/schema/vrs-source.yaml#L393-L395):

```
  SequenceReference:
    maturity: Alpha
    inherits: ValueObject
```

This class should inherit ValueObject, not Ga4ghIdentifiableObject.

**Comment by korikuzma** [comment]
@ahwagner  do you have thoughts on the `SequenceReference` example? 

I'm thinking it should be:

```yaml
    in:
      type: SequenceReference
      refgetAccession: SQ.F-LrLMe1SRpfUZHkQmvkVKFEGaoDeHul
    out:
      ga4gh_digest: F-LrLMe1SRpfUZHkQmvkVKFEGaoDeHul
      ga4gh_identify: ga4gh:SQ.F-LrLMe1SRpfUZHkQmvkVKFEGaoDeHul
      ga4gh_serialize: null
```

**Comment by korikuzma** [comment]
@ahwagner made small change to LSE and explicitly had ga4gh_serialize/ga4gh_identify return null for SequenceReference

**Review by ahwagner — APPROVED** [review]
All looks good to me with the caveat that I did not verify hash correctness. Let me know if this is needed.

**Comment by korikuzma** [comment]
> All looks good to me with the caveat that I did not verify hash correctness. Let me know if this is needed.

I run through vrs-python and did not make changes to `sha512t24u`. I'll merge. Thanks for the quick PR review @ahwagner and @larrybabb

**Pull request merged**
